name: Versions Update

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/version_update.yml'
  schedule:
    # Run at 02:00 on the first of the month
    - cron: '0 2 1 * *'

jobs:
  update_versions:
    name: Versions Update
    runs-on: ubuntu-latest
    container: debian:12
    permissions:
      actions: write
      contents: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache local .m2
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-fetch-depth: 0
          java-distribution: 'temurin'
          java-version: '24'
          maven-version: '3.9.11'

      - name: Update project versions
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            bash \
            gawk \
            grep \
            jq \
            curl \
            ca-certificates

          bash .github/scripts/update_dependency_versions.sh

      - name: Save workspace for next job
        uses: actions/upload-artifact@v4
        with:
          name: updated_versions-workspace
          path: .

  check_git_changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    needs: update_versions
    permissions:
      actions: write
      contents: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache local .m2
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-fetch-depth: 0
          java-distribution: 'temurin'
          java-version: '24'
          maven-version: '3.9.11'

      - name: Download updated workspace
        uses: actions/download-artifact@v5
        with:
          name: updated_versions-workspace
          path: .

      - name: Check for changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Run linters and unit/integration tests
        id: application_tests
        if: env.has_changes == 'true'
        run: |
          mvn clean install -Dall
          bash .github/scripts/python_lint_and_tests.sh

      - name: Commit changes
        id: change_commit
        if: env.has_changes == 'true'
        run: |
          git config user.name github-actions
          git config user.email "actions@github.com"
          git add .
          git commit -m '[CI] Updating versions'

      - name: Push changes
        if: env.has_changes == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.PUSH_PAT }}
          branch: master
